### ISSUE TITLE
请问如何固化3个网络到一个.pb文件中呢？

### ISSUE THREAD

**Issue by sharepointer** [vcvycy/MTCNN4Android#2]

**Comment by vcvycy** [comment]
直接搞就好了，3个网络是在同一张graph里的。

**Comment by vcvycy** [comment]
对tensorflow来说，并没有几个网络的说法；里面就是节点和边，节点可以属于这个网络，也可以属于那个网络，只要你把所需要的output依赖的placeholder传进去就行。

**Comment by sharepointer** [comment]
嗯嗯
