### ISSUE TITLE
输入到网络前为什么要对图像翻转？

### ISSUE THREAD

**Issue by wenhuazang** [vcvycy/MTCNN4Android#7]
您好，输入到网络前为什么要对图像延对角线翻转？

**Comment by vcvycy** [comment]
主要原因是：网络训练的时候，图像竖坐标是第一维，横坐标是第二维；
而图像由Java/python载入时，刚好相反；
所以需要沿着对角线翻转。
当然你可以自己训练一个不需要对折的模型。

**Comment by wenhuazang** [comment]
> 主要原因是：网络训练的时候，图像竖坐标是第一维，横坐标是第二维；
> 而图像由Java/python载入时，刚好相反；
> 所以需要沿着对角线翻转。
> 当然你可以自己训练一个不需要对折的模型。

明白啦，多谢
